print("\t ______ ")
print("\t|      |")
print("\t| (OO) |")
print("\t|  @   |")
print("\t| ___  |")
print("\t|______|")
print("\t   #")
print("---------------")
print("|             |")
print("|             |")
print("|             |")
print("|             |")
print("|             |")
print("_______________")

eye = input("\nPlease enter a character for the eye\n")

print("\t ______ ")
print("\t|      |")
print(f"\t| ({eye}{eye}) |")
print("\t|  @   |")
print("\t| ___  |")
print("\t|______|")
print("\t   #")
print("---------------")
print("|             |")
print("|             |")
print("|             |")
print("|             |")
print("|             |")
print("_______________")